import { generateSlug } from "@/shared/lib/generateSlug";
import { ProductEntity } from "./entities";
import AboutBird from "@/shared/images/about-bird.jpg";

export const productsArray: ProductEntity[] = [
  {
    id: "1",
    name: "Almond Milk",
    slug: generateSlug("Almond Milk"),
    description: "A nutty milk alternative rich in Vitamin E.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "2",
    name: "Soy Candle",
    slug: generateSlug("Soy Candle"),
    description: "Eco-friendly candle made from soy wax with a soothing aroma.",
    images: [AboutBird, AboutBird, AboutBird, AboutBird, AboutBird],
  },
  {
    id: "3",
    name: "Olive Oil",
    slug: generateSlug("Olive Oil"),
    description:
      "Extra virgin olive oil with a rich taste and high in antioxidants.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "4",
    name: "Maple Syrup",
    slug: generateSlug("Maple Syrup"),
    description: "Pure maple syrup perfect for pancakes and waffles.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "5",
    name: "Blueberry Jam",
    slug: generateSlug("Blueberry Jam"),
    description: "Sweet and delicious jam made from fresh blueberries.",
    images: [AboutBird, AboutBird, AboutBird, AboutBird, AboutBird],
  },
  {
    id: "6",
    name: "Almond Milk",
    slug: generateSlug("Almond Milk"),
    description: "A nutty milk alternative rich in Vitamin E.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "7",
    name: "Soy Candle",
    slug: generateSlug("Soy Candle"),
    description: "Eco-friendly candle made from soy wax with a soothing aroma.",
    images: [AboutBird, AboutBird, AboutBird, AboutBird, AboutBird],
  },
  {
    id: "8",
    name: "Olive Oil",
    slug: generateSlug("Olive Oil"),
    description:
      "Extra virgin olive oil with a rich taste and high in antioxidants.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "9",
    name: "Maple Syrup",
    slug: generateSlug("Maple Syrup"),
    description: "Pure maple syrup perfect for pancakes and waffles.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "10",
    name: "Blueberry Jam",
    slug: generateSlug("Blueberry Jam"),
    description: "Sweet and delicious jam made from fresh blueberries.",
    images: [AboutBird, AboutBird, AboutBird, AboutBird, AboutBird],
  },
  {
    id: "11",
    name: "Almond Milk",
    slug: generateSlug("Almond Milk"),
    description: "A nutty milk alternative rich in Vitamin E.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "12",
    name: "Soy Candle",
    slug: generateSlug("Soy Candle"),
    description: "Eco-friendly candle made from soy wax with a soothing aroma.",
    images: [AboutBird, AboutBird, AboutBird, AboutBird, AboutBird],
  },
  {
    id: "13",
    name: "Olive Oil",
    slug: generateSlug("Olive Oil"),
    description:
      "Extra virgin olive oil with a rich taste and high in antioxidants.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "14",
    name: "Maple Syrup",
    slug: generateSlug("Maple Syrup"),
    description: "Pure maple syrup perfect for pancakes and waffles.",
    images: [
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
      AboutBird,
    ],
  },
  {
    id: "15",
    name: "Blueberry Jam",
    slug: generateSlug("Blueberry Jam"),
    description: "Sweet and delicious jam made from fresh blueberries.",
    images: [AboutBird, AboutBird, AboutBird, AboutBird, AboutBird],
  },
];
